// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/model.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Doc struct {
	Category             string   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Doc) Reset()         { *m = Doc{} }
func (m *Doc) String() string { return proto.CompactTextString(m) }
func (*Doc) ProtoMessage()    {}
func (*Doc) Descriptor() ([]byte, []int) {
	return fileDescriptor_312ac5bcab6cbb43, []int{0}
}

func (m *Doc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Doc.Unmarshal(m, b)
}
func (m *Doc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Doc.Marshal(b, m, deterministic)
}
func (m *Doc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Doc.Merge(m, src)
}
func (m *Doc) XXX_Size() int {
	return xxx_messageInfo_Doc.Size(m)
}
func (m *Doc) XXX_DiscardUnknown() {
	xxx_messageInfo_Doc.DiscardUnknown(m)
}

var xxx_messageInfo_Doc proto.InternalMessageInfo

func (m *Doc) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Doc) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Doc) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_312ac5bcab6cbb43, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Datasource struct {
	Index                string               `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string               `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Datasource) Reset()         { *m = Datasource{} }
func (m *Datasource) String() string { return proto.CompactTextString(m) }
func (*Datasource) ProtoMessage()    {}
func (*Datasource) Descriptor() ([]byte, []int) {
	return fileDescriptor_312ac5bcab6cbb43, []int{2}
}

func (m *Datasource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Datasource.Unmarshal(m, b)
}
func (m *Datasource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Datasource.Marshal(b, m, deterministic)
}
func (m *Datasource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Datasource.Merge(m, src)
}
func (m *Datasource) XXX_Size() int {
	return xxx_messageInfo_Datasource.Size(m)
}
func (m *Datasource) XXX_DiscardUnknown() {
	xxx_messageInfo_Datasource.DiscardUnknown(m)
}

var xxx_messageInfo_Datasource proto.InternalMessageInfo

func (m *Datasource) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Datasource) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Datasource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DatasourceList struct {
	Datasource           []*Datasource `protobuf:"bytes,1,rep,name=datasource,proto3" json:"datasource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DatasourceList) Reset()         { *m = DatasourceList{} }
func (m *DatasourceList) String() string { return proto.CompactTextString(m) }
func (*DatasourceList) ProtoMessage()    {}
func (*DatasourceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_312ac5bcab6cbb43, []int{3}
}

func (m *DatasourceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatasourceList.Unmarshal(m, b)
}
func (m *DatasourceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatasourceList.Marshal(b, m, deterministic)
}
func (m *DatasourceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatasourceList.Merge(m, src)
}
func (m *DatasourceList) XXX_Size() int {
	return xxx_messageInfo_DatasourceList.Size(m)
}
func (m *DatasourceList) XXX_DiscardUnknown() {
	xxx_messageInfo_DatasourceList.DiscardUnknown(m)
}

var xxx_messageInfo_DatasourceList proto.InternalMessageInfo

func (m *DatasourceList) GetDatasource() []*Datasource {
	if m != nil {
		return m.Datasource
	}
	return nil
}

type UserKeys struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserKeys) Reset()         { *m = UserKeys{} }
func (m *UserKeys) String() string { return proto.CompactTextString(m) }
func (*UserKeys) ProtoMessage()    {}
func (*UserKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_312ac5bcab6cbb43, []int{4}
}

func (m *UserKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserKeys.Unmarshal(m, b)
}
func (m *UserKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserKeys.Marshal(b, m, deterministic)
}
func (m *UserKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserKeys.Merge(m, src)
}
func (m *UserKeys) XXX_Size() int {
	return xxx_messageInfo_UserKeys.Size(m)
}
func (m *UserKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_UserKeys.DiscardUnknown(m)
}

var xxx_messageInfo_UserKeys proto.InternalMessageInfo

func (m *UserKeys) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserSettings struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSettings) Reset()         { *m = UserSettings{} }
func (m *UserSettings) String() string { return proto.CompactTextString(m) }
func (*UserSettings) ProtoMessage()    {}
func (*UserSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_312ac5bcab6cbb43, []int{5}
}

func (m *UserSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSettings.Unmarshal(m, b)
}
func (m *UserSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSettings.Marshal(b, m, deterministic)
}
func (m *UserSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSettings.Merge(m, src)
}
func (m *UserSettings) XXX_Size() int {
	return xxx_messageInfo_UserSettings.Size(m)
}
func (m *UserSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSettings.DiscardUnknown(m)
}

var xxx_messageInfo_UserSettings proto.InternalMessageInfo

func (m *UserSettings) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserSettings) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*Doc)(nil), "model.Doc")
	proto.RegisterType((*Empty)(nil), "model.Empty")
	proto.RegisterType((*Datasource)(nil), "model.Datasource")
	proto.RegisterType((*DatasourceList)(nil), "model.DatasourceList")
	proto.RegisterType((*UserKeys)(nil), "model.UserKeys")
	proto.RegisterType((*UserSettings)(nil), "model.UserSettings")
}

func init() {
	proto.RegisterFile("model/model.proto", fileDescriptor_312ac5bcab6cbb43)
}

var fileDescriptor_312ac5bcab6cbb43 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x6a, 0xdb, 0x40,
	0x14, 0x86, 0xb1, 0x54, 0xd7, 0xf6, 0xb3, 0xeb, 0xe2, 0x69, 0x0b, 0xaa, 0x5a, 0xa8, 0x3b, 0x8b,
	0xe2, 0x45, 0xd1, 0x50, 0xb5, 0x8b, 0x2e, 0x0b, 0xb5, 0xf1, 0xa2, 0xdd, 0xd4, 0x4d, 0x0e, 0x30,
	0x96, 0x9e, 0xc5, 0x80, 0xa4, 0x11, 0x9a, 0x31, 0xc4, 0x84, 0x6c, 0x72, 0x85, 0x1c, 0x2d, 0x57,
	0xc8, 0x41, 0xc2, 0x8c, 0x46, 0x96, 0x20, 0x90, 0x8d, 0xd0, 0xff, 0xf4, 0xeb, 0xd7, 0xf7, 0x3f,
	0x0d, 0x2c, 0x0a, 0x99, 0x62, 0xce, 0xec, 0x35, 0xaa, 0x6a, 0xa9, 0x25, 0x19, 0x5a, 0x11, 0x7e,
	0xcc, 0xa4, 0xcc, 0x72, 0x64, 0xbc, 0x12, 0x8c, 0x97, 0xa5, 0xd4, 0x5c, 0x0b, 0x59, 0xaa, 0xc6,
	0x14, 0x7e, 0x72, 0x4f, 0xad, 0xda, 0x1f, 0x0f, 0x4c, 0x8b, 0x02, 0x95, 0xe6, 0x45, 0xd5, 0x18,
	0xe8, 0x06, 0xfc, 0xb5, 0x4c, 0x48, 0x08, 0xe3, 0x84, 0x6b, 0xcc, 0x64, 0x7d, 0x0a, 0x06, 0xcb,
	0xc1, 0x6a, 0xb2, 0x3b, 0x6b, 0x32, 0x07, 0x4f, 0xa4, 0x81, 0x67, 0xa7, 0x9e, 0x48, 0x09, 0x81,
	0x17, 0x25, 0x2f, 0x30, 0xf0, 0xed, 0xc4, 0xde, 0xd3, 0x11, 0x0c, 0x37, 0x45, 0xa5, 0x4f, 0x34,
	0x07, 0x58, 0x73, 0xcd, 0x95, 0x3c, 0xd6, 0x09, 0x92, 0xb7, 0x30, 0x14, 0x65, 0x8a, 0x57, 0x2e,
	0xb3, 0x11, 0xe4, 0x27, 0x4c, 0xce, 0x18, 0x36, 0x77, 0x1a, 0x87, 0x51, 0x03, 0x1a, 0xb5, 0xa0,
	0xd1, 0x45, 0xeb, 0xd8, 0x75, 0x66, 0x87, 0xe2, 0xb7, 0x28, 0xf4, 0x37, 0xcc, 0xbb, 0xaf, 0xfd,
	0x15, 0x4a, 0x93, 0x6f, 0x00, 0xe9, 0x79, 0x12, 0x0c, 0x96, 0xfe, 0x6a, 0x1a, 0x2f, 0xa2, 0x66,
	0x6f, 0x9d, 0x75, 0xd7, 0x33, 0xd1, 0x2f, 0x30, 0xbe, 0x54, 0x58, 0xff, 0xc1, 0x93, 0x32, 0x7b,
	0x38, 0x2a, 0xac, 0x6d, 0x3f, 0xb7, 0x87, 0x56, 0xd3, 0x5f, 0x30, 0x33, 0xbe, 0xff, 0xa8, 0xb5,
	0x28, 0xb3, 0x67, 0xbd, 0xa6, 0x38, 0x16, 0x5c, 0xe4, 0x6e, 0x6d, 0x8d, 0x88, 0xf7, 0xf0, 0xaa,
	0xc7, 0x50, 0x25, 0xe4, 0x1f, 0x8c, 0xb6, 0xa8, 0x2d, 0xf8, 0xcc, 0x41, 0xda, 0x35, 0x86, 0xef,
	0x9e, 0x20, 0x1b, 0x13, 0xfd, 0x7c, 0x7b, 0xff, 0x70, 0xe7, 0x7d, 0x20, 0xef, 0x99, 0xe5, 0xd7,
	0xb2, 0x46, 0x56, 0xe4, 0xac, 0x2b, 0xa3, 0xe2, 0x1c, 0x46, 0x86, 0xd2, 0xa4, 0x73, 0xf0, 0xb7,
	0xa8, 0xc9, 0x6b, 0x97, 0xd5, 0x96, 0x0c, 0xdf, 0xf4, 0x06, 0x6d, 0x1b, 0xfa, 0xc3, 0x46, 0x47,
	0xe4, 0x6b, 0x2f, 0xda, 0xd4, 0x51, 0xec, 0xba, 0x6d, 0x75, 0x63, 0x8e, 0xd1, 0x41, 0xe4, 0xc8,
	0x94, 0x7b, 0x6b, 0xff, 0xd2, 0xfe, 0xaf, 0xef, 0x8f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x48,
	0x66, 0x2c, 0xa0, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DatasourceRpcClient is the client API for DatasourceRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DatasourceRpcClient interface {
	GetList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DatasourceList, error)
}

type datasourceRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewDatasourceRpcClient(cc grpc.ClientConnInterface) DatasourceRpcClient {
	return &datasourceRpcClient{cc}
}

func (c *datasourceRpcClient) GetList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DatasourceList, error) {
	out := new(DatasourceList)
	err := c.cc.Invoke(ctx, "/model.DatasourceRpc/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatasourceRpcServer is the server API for DatasourceRpc service.
type DatasourceRpcServer interface {
	GetList(context.Context, *Empty) (*DatasourceList, error)
}

// UnimplementedDatasourceRpcServer can be embedded to have forward compatible implementations.
type UnimplementedDatasourceRpcServer struct {
}

func (*UnimplementedDatasourceRpcServer) GetList(ctx context.Context, req *Empty) (*DatasourceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}

func RegisterDatasourceRpcServer(s *grpc.Server, srv DatasourceRpcServer) {
	s.RegisterService(&_DatasourceRpc_serviceDesc, srv)
}

func _DatasourceRpc_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasourceRpcServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.DatasourceRpc/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasourceRpcServer).GetList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _DatasourceRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.DatasourceRpc",
	HandlerType: (*DatasourceRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _DatasourceRpc_GetList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model/model.proto",
}

// UserRpcClient is the client API for UserRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserRpcClient interface {
	Get(ctx context.Context, in *UserKeys, opts ...grpc.CallOption) (*UserSettings, error)
}

type userRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRpcClient(cc grpc.ClientConnInterface) UserRpcClient {
	return &userRpcClient{cc}
}

func (c *userRpcClient) Get(ctx context.Context, in *UserKeys, opts ...grpc.CallOption) (*UserSettings, error) {
	out := new(UserSettings)
	err := c.cc.Invoke(ctx, "/model.UserRpc/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRpcServer is the server API for UserRpc service.
type UserRpcServer interface {
	Get(context.Context, *UserKeys) (*UserSettings, error)
}

// UnimplementedUserRpcServer can be embedded to have forward compatible implementations.
type UnimplementedUserRpcServer struct {
}

func (*UnimplementedUserRpcServer) Get(ctx context.Context, req *UserKeys) (*UserSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterUserRpcServer(s *grpc.Server, srv UserRpcServer) {
	s.RegisterService(&_UserRpc_serviceDesc, srv)
}

func _UserRpc_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserKeys)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.UserRpc/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).Get(ctx, req.(*UserKeys))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.UserRpc",
	HandlerType: (*UserRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _UserRpc_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model/model.proto",
}
